from elasticsearch import Elasticsearch
import json

def insert_article(es_instance, index_name, article):
    es_instance.index(index=index_name, body=article)

def insert_articles(es_instance, index_name, articles):
    for article in articles:
        insert_article(es_instance, index_name, article)

if __name__ == "__main__":
    es = Elasticsearch([{"host": "localhost", "port": 9200, "scheme": "http"}])
    index_name = "news_articles"

    # Replace this with your desired articles
    articles_to_insert = [
        {'title': 'India looks at expanding rupee trade to Africa, W Asia to make it stronger',
  'text': ['India seeks to expand rupee trade with Russia, African countries, UAE, Saudi Arabia, and Sri Lanka.',
   "Increased rupee trading would reduce India's dependence on foreign exchange reserves.",
   "Expanded rupee trading could strengthen the rupee, reducing exchange rate fluctuations' impact."],
  'link': 'https://www.business-standard.com/article/economy-policy/india-looks-at-expanding-rupee-trade-to-africa-w-asia-to-make-it-stronger-122122101110_1.html'},
 {'title': "Lula floats shared 'trading currency' during Argentina trip",
  'text': ['Brazil and Argentina discuss shared unit of value for bilateral trade to reduce reliance on the U.S. dollar.',
   'Brazilian President Lula and Argentine President Fernandez emphasize that the shared currency would not replace existing currencies.',
   "The shared currency proposal aims to boost bilateral trade through more Brazilian export financing backed by Argentina's international collateral."],
  'link': 'https://www.reuters.com/world/americas/brazil-argentina-encourage-trade-says-haddad-plays-down-common-currency-2023-01-23/'},
 {'title': 'The Pan-African Payments and Settlement System',
  'text': ['PAPSS is a centralized financial market infrastructure enabling efficient and secure money flow across African borders.',
   'PAPSS collaborates with central banks, commercial banks, and fintech organizations across Africa.',
   'The platform reduces high-cost correspondent banking relationships, expands financial inclusion, and monitors funds transfers.'],
  'link': 'https://au-afcfta.org/operational-instruments/papss/'},
 {'title': 'Saudi Arabia Open to Talks on Trade in Non-US Dollar Currencies',
  'text': ['Saudi Arabia expresses openness to discuss trade in currencies other than the U.S. dollar.'],
  'link': 'https://www.bloomberg.com/news/articles/2023-01-17/saudi-arabia-open-to-talks-on-trade-in-currencies-besides-dollar#xj4y7vzkg'},
 {'title': 'The Decline in Manufacturing Jobs: Not Necessarily a Cause for Concern',
  'text': ['Manufacturing job decline not necessarily harmful to economic growth or an increase in inequality with proper policies.',
   'Shifts in economic activity and productivity are part of a natural process of structural transformation.',
   'Policymakers should focus on reskilling displaced workers, reducing reallocation costs, and strengthening safety nets.'],
  'link': 'https://www.imf.org/en/Blogs/Articles/2018/04/09/the-decline-in-manufacturing-jobs-not-necessarily-a-cause-for-concern'},
 {'title': "China's SMIC Shipping 7nm Chips, Reportedly Copied TSMC's Tech",
  'text': ['Chinese foundry SMIC has been producing 7nm process node chips for a Bitcoin Miner SoC.',
   "TechInsights reverse-engineered the chip and found similarities to TSMC's 7nm process technology.",
   "TSMC, Intel, and Samsung are at least two nodes ahead of SMIC's 7nm technology.",
   'SMIC has been heavily sanctioned by the US government, affecting its access to advanced EUV chipmaking tools.',
   "SMIC's Minerva Bitcoin mining chip is basic and implies early stages of chip development."],
  'link': 'https://www.tomshardware.com/news/china-chipmaker-smics-7nm-process-is-reportedly-copied-from-tsmc-tech'},
 {'title': 'Huawei EUV Scanner Patent Suggests Sub-7nm Chips for China',
  'text': ['Huawei filed a patent application for an extreme ultraviolet (EUV) lithography scanner.',
   'If successful, it could enable Chinese chipmakers to produce sub-7nm-class technologies.',
   'Developing an EUV scanner is highly complex and requires many state-of-the-art components.',
   'ASML is the only company that has successfully developed an EUV scanner.',
   "Huawei's semiconductor production ambitions also include building wafer fab equipment."],
  'link': 'https://www.tomshardware.com/news/huawe-euv-scanner'},
 {'title': "Is India's Economy Going Backwards?",
  'text': ["India's factory sector has collapsed over the last 5-6 years.",
   'Manufacturing slowdown began before COVID, and growth has not resumed post-lockdown.',
   'The video explains the reasons behind the manufacturing decline.'],
  'link': "https://www.newsclick.in/indias-economy-going-backwards-aunindyo-chakravarty#:~:text=in%20your%20browser.-,India's%20factory%20sector%20has%20completely%20collapsed%20in%20the%20last%205,know%20why%20this%20is%20happening."},
 {'title': 'A new chapter: New wave of cross-border migrant workers reentering China after border reopening sparks hopes of social, economic recovery',
  'text': ['China-Myanmar and China-Vietnam border cities, Ruili and Hekou, witness influx of cross-border migrant workers after reopening.',
   'Border checkpoints closed for almost three years due to COVID-19.',
   'Returning migrant workers expected to boost local economies and contribute to economic recovery.',
   'Myanmar nationals form the largest flow of cross-border human traffic at Ruili port, with many involved in the jade and jewelry industry.',
   'Workers from Myanmar and Vietnam attracted to China for better job opportunities, higher salaries, and stable wages.'],
  'link': 'https://www.globaltimes.cn/page/202301/1283965.shtml'},
 {'title': '25+ Striking U.S. Film Industry Statistics [2023]: Facts About The Video Production Industry In The U.S.',
  'text': ['Domestic box office revenue reached $7.37 billion in 2022.',
   'U.S. film industry expected to experience a CAGR of 8.3% between 2021 to 2027.',
   'COVID-19 Pandemic significantly impacted the industry, with box office revenue down 82% from 2019.',
   'Streaming services grew by 37% in 2020, with their market worth $24 billion.',
   'Film industry employs about 2.5 million people and pays out $188 billion per year in wages.',
   'Top Gun: Maverick was the top-grossing movie of 2022, earning $718.7 million.'],
  'link': 'https://www.zippia.com/advice/us-film-industry-statistics/'},
 {'title': 'Journalism Jobs Are Declining and Often Don’t Pay Well, Georgetown CEW Report Says',
  'text': ['More than one-third of journalism jobs will be lost between 2002 and 2031.',
   'Decades of decline due to newspaper downsizing and closures.',
   'Journalists face a competitive job market.',
   'Demographics of journalists are changing.',
   'Financial payoffs for journalism and communication majors are moderate compared to other majors.'],
  'link': 'https://finance.yahoo.com/news/journalism-jobs-declining-often-don-060000731.html#:~:text=Projected%20job%20losses%20for%20journalists,publishers%20has%20fallen%20by%2063%25.'},
 {'title': 'As newspapers close, struggling communities are hit hardest by the decline in local journalism',
  'text': ['US loses newspapers at a rate of two per week.',
   'Economically struggling communities are most affected.',
   '70 million residents have limited or no access to local news.',
   'News deserts contribute to lower voter participation and increased corruption.',
   'New digital sites and nonprofit models show signs of hope.'],
  'link': 'https://news.northwestern.edu/stories/2022/06/newspapers-close-decline-in-local-journalism'},
 {'title': 'U.S. newsroom employment has fallen 26% since 2008',
  'text': ['Newsroom employment in the US dropped by 26% between 2008 and 2020.',
   'Newspapers saw significant job losses, while digital-native news organizations experienced gains.',
   'Newspaper newsroom employment fell 57% during this period.',
   'Digital-native newsroom employment increased by 144%, but still remained below the newspaper sector.'],
  'link': 'https://www.pewresearch.org/fact-tank/2021/07/13/u-s-newsroom-employment-has-fallen-26-since-2008/'},
 {'title': 'Why is France being told to leave Burkina Faso?',
  'text': ["Burkina Faso's military government asked French troops to leave the country within one month.",
   'French forces are in Burkina Faso as part of a campaign against rebel groups.',
   'Thousands have been killed and nearly three million displaced since 2015 due to violence linked to al-Qaeda and ISIL (ISIS) groups.',
   "Demonstrations against the French soldiers' presence have been held in the capital, Ouagadougou."],
  'link': 'https://www.aljazeera.com/program/inside-story/2023/1/23/why-is-france-being-kicked-out-of-burkina-faso'},
 {'title': 'Paris gets kicked out of French Africa',
  'text': ["Mali's government announced it is tearing up defense agreements with France.",
   "France continues to withdraw its military from Mali following the Malian government's call.",
   'Anti-French demonstrations have intensified in Burkina Faso, with Russian flags appearing in the streets.',
   'French military has been implicated in numerous crimes in various African countries.'],
  'link': 'https://www.newagebd.net/article/170318/paris-gets-kicked-out-of-french-africa'},
 {'title': 'Why are French troops leaving Mali, and what will it mean for the region?',
  'text': 'French President Emmanuel Macron has announced he will be pulling French forces out of the West African nation of Mali, where they have been fighting Islamist militants since 2013. Here are the key points to know: Islamic State and al-Qaeda have decided to focus on the Sahel region of Africa. Ansaroul Islam and Boko Haram are two other jihadist groups active in the Sahel. France sent 5,000 troops to Mali in 2013 to face an armed rebellion. The French presence became unpopular due to the increased number of terror attacks and Malians joining insurgent groups. France refused to negotiate a peace deal with Islamist groups. The French troops involved in Operation Barkhane will be withdrawn over the next four to six months. France will deploy troops in other countries in the Sahel.',
  'link': 'https://www.bbc.com/news/world-60419799'},
 {'title': 'Last French troops leave Central African Republic amid closer Bangui-Moscow ties',
  'text': "The last French troops deployed in the Central African Republic left on Thursday following a chill in relations caused by closer ties between Bangui and Moscow. Here are the key points to know: France dispatched up to 1,600 troops to help stabilise the country after a coup in 2013. The operation, named Sangaris, was France's seventh military intervention in the CAR since the country gained independence in 1960. The French troops in the CAR provided logistics for the European Union Training Mission and a contingent of the UN peacekeeping mission in the Central African Republic (MINUSCA). Paris last year decided to suspend military cooperation with Bangui. French troops withdrew from former colony Mali earlier this year. CAR ranks among the poorest and most unstable countries in the world.",
  'link': 'https://www.france24.com/en/africa/20221215-last-french-troops-leave-central-african-republic-amid-closer-bangui-moscow-ties'},
 {'title': 'Russia-Pakistan energy collaboration defeats the Western sanctions',
  'text': "- Pakistan and Russia agreed to begin crude oil supply to Pakistan by March this year amid a deepening energy and reserve crisis.\n- Transactions between Moscow and Islamabad must be done in the currency of friendly countries instead of the US dollar.\n- Russian and Pakistani officials also discussed reviving the proposed Stream Gas Pipeline Project.\n- Pakistani State Minister for Petroleum Musadik Malik flew to Moscow to deliberate on the energy deal. Malik told the media on his return that Russia would provide Pakistan with crude oil at discounted rates.\n- The pipeline's designed annual capacity was estimated at 12.4 billion cubic meters (bcm), with the potential for further expansion to 16 bcm. The cost estimates range from $1.5 billion to $3.5 billion, with Moscow funding 26% and Islamabad proposing to fund the remaining 74%.",
  'link': 'https://english.almayadeen.net/articles/analysis/russia-pakistan-energy-collaboration-defeats-the-western-san'},
 {'title': "Walmart's multi-cloud strategy cuts millions in IT costs",
  'text': "- Walmart advises companies to have choices for managing the costs of running workloads on cloud providers.\n- Walmart has built a hybrid cloud architecture designed to run workloads on Azure, Google Cloud or Walmart's Cloud Native Platform.\n- The Cloud Native Platform's abstraction layer hides the differences between spinning up resources on the three platforms, and the universal interface lets developers deploy and move workloads using nearly the same procedures.\n- Walmart's neutralizing abstraction layer has lowered cloud spending by between 10% and 18%.\n- The unification of multi-cloud management tackles the complexity of moving data between public clouds and individual applications on private IT environments.",
  'link': 'https://www.techtarget.com/searchcloudcomputing/news/252522631/Walmarts-multi-cloud-strategy-cuts-millions-in-IT-costs'},
 {'title': 'StemDrop launch: TikTok wants to change how music is released',
  'text': 'TikTok has partnered with Simon Cowell and Max Martin to launch StemDrop, a new platform that lets artists publish the stems of their songs alongside full single releases, allowing other people to immediately create remixes and samples from the new track. StemDrop will officially launch next week with the exclusive TikTok release of 60 seconds of a new single by Max Martin, Savan Kotecha and Ali Payami. The renewed popularity of Kate Bush’s ‘Running Up That Hill’ after it featured in a Stranger Things episode was in part thanks to the over 500,000 TikTok videos posted of the song.',
  'link': 'https://www.euronews.com/culture/2022/10/19/stemdrop-launch-tiktok-wants-to-change-how-music-is-released'},
 {'title': "China's Guangzhou plans 1,722 projects worth $945 bln",
  'text': ['Guangzhou plans 1,722 projects worth more than 6.5 trillion yuan ($945 billion).',
   'Projects span areas including infrastructure, new energy vehicles and biomedicine.'],
  'link': 'https://www.reuters.com/article/china-economy-infrastructure-guangzhou/chinas-guangzhou-plans-1722-projects-worth-945-bln-idINB8N33D00H'},
 {'title': 'Pakistan and Iran: The potential for a great alliance',
  'text': ['Pak-Iran relations have soured throughout the years.',
   'The biggest challenges Pakistan faces when it comes to Iran is pressure from its ally, the United States.',
   'Growing signs of rapprochement between Saudi Arabia and Iran.',
   'The proposed Pakistan-Iran (IP) gas pipeline can mutually benefit both sides simultaneously.',
   'Providing 22 million cubic metres of gas a day, and electricity generation equivalent to nearly 4,500 megawatts, the pipeline would be able to meet nearly all of Pakistan’s current electricity shortfall.',
   'The IP gas pipeline can cement Pak-Iran relations and effectively thwart expanding Indian influence in the region.',
   'For Iran, the IP gas pipeline could provide much-needed relief to its ailing economy.'],
  'link': 'https://tribune.com.pk/article/97602/pakistan-and-iran-the-potential-for-a-great-alliance'},
 {'title': 'Ukraine warns Russia massing 500,000 troops on border for offensive',
  'text': 'Ukrainian Defense Minister says Russia has 500,000 troops ready for an attack in weeks, far higher than the 300,000 newly enlisted soldiers Russian President called up this past autumn. Ukrainian officials worry Moscow’s military is preparing for a soon-to-come assault aimed at turning the war in the Kremlin’s favor. Western and Ukrainian officials have long warned that Russia is planning a renewed spring offensive after a series of embarrassing defeats in summer and fall and a near stalemate over the winter.',
  'link': 'https://thehill.com/policy/defense/3841230-ukraine-warns-russia-massing-500000-troops-on-border-for-offensive/'},
 {'title': 'Indonesia Ratifies RCEP Trade Agreement',
  'text': "Indonesia has ratified the Regional Comprehensive Economic Partnership (RCEP) agreement, which will take effect in the country from Jan 1, 2022. The RCEP, comprising of 15 Asia-Pacific countries, is the world's largest trade pact, accounting for about 30 percent of the world's population, gross domestic product and trade.",
  'link': 'https://www.aseanbriefing.com/news/indonesia-ratifies-rcep-trade-agreement/'},
 {'title': 'Governor: 2 people killed, 5 injured by Russian shelling of Chasiv Yar, Donetsk Oblast',
  'text': 'Russian shelling of Chasiv Yar, a city in the eastern Ukrainian Donetsk Oblast, killed two people and injured five. Dozens of residential and public buildings, as well as cars, were damaged in Chasiv Yar. Russian forces also shelled Avdiivka, Toretsk, Oleksandropol, and Bohoiavlenka on Jan. 27.',
  'link': 'https://news.yahoo.com/governor-2-people-killed-5-132727203.html'},
 {'title': 'How has global influence in the Middle East shifted?',
  'text': "China and Saudi Arabia have signed agreements, marking a shift in Saudi Arabia's historically strong relationship with the United States. Russia's support for Syrian President Bashar Al-Assad has contributed to the Syrian President successfully retaining power, despite international pressure and attempts to oust him. The Syrian President has reestablished connections with other Arab countries, such as the UAE, Saudi Arabia, and Egypt. Iranian President Ebrahim Raisi announced that all Russian banks and 106 banks in 13 other countries have been connected to Iran's financial messaging system known as SEPAM.",
  'link': 'https://english.almayadeen.net/articles/blog/how-has-global-influence-in-the-middle-east-shifted'},
 {'title': "Iran says all Russian banks connected to Iran's financial messaging system",
  'text': "All Russian banks and 106 banks in 13 other countries have been connected to Iran's financial messaging system known as SEPAM. Iranian banks are no longer in need of the Society for Worldwide Interbank Financial Telecommunication (SWIFT) network. The Central Bank of Iran and the Bank of Russia signed a deal to connect SEPAM and the Financial Messaging System of the Bank of Russia known as SPFS. The move was the first step of the joint action plan for banking cooperation between Iran and Russia agreed by the two countries' central banks last year.",
  'link': 'https://english.news.cn/20230203/4b765428fe8e49c79f39b1648f7a1575/c.html'},
 {'title': "Egypt's Parliament endorses pact to join Brics Bank",
  'text': "Egypt has endorsed the agreement that allows it to officially join the New Development Bank set up by Brics. The move is expected to give a big push to intra-Brics trade in national currencies, enabling member states to safeguard their foreign exchange reserves. Joining Brics and its development bank benefits Egypt by providing financial and technical assistance in areas of sustainable development, health, infrastructure, transport, water, and telecommunications. Egypt's joining of the Brics group's New Development Bank will also relieve the state budget of the pressure of finding US dollars to meet the country's imports.",
  'link': 'https://economictimes.indiatimes.com/news/international/world-news/egypts-parliament-endorses-pact-to-join-brics-bank/articleshow/97502850.cms'},
 {'title': 'Iran, Argentina’s applications to BRICS underscores pursuit of development, solidarity',
  'text': "- Iran and Argentina have formally submitted their applications to become members of BRICS\n- Chinese analysts believe that it underscores the pursuit by developing and emerging countries of development not disturbance\n- Including Iran in BRICS will mean closer and more effective channels between resources and markets\n- Argentina's inclusion would also help promote cooperation between BRICS and other regional countries in Latin America",
  'link': 'https://www.globaltimes.cn/page/202206/1269270.shtml'},
 {'title': '”Ekonomin hackar och ingen förbättring är i sikte”',
  'text': 'Sorry, I cannot summarize this article as it appears to be a subscription page and does not contain any news content.',
  'link': 'https://www.di.se/nyheter/ekonomin-hackar-och-ingen-forbattring-ar-i-sikte/'},
 {'title': "China's imports and exports of 2022 hit a new record",
  'text': "China's total goods imports and exports surged 7.7 percent YoY to 42.07 trillion yuan ($6.26 trillion) in 2022, hitting a new record. Exports jumped 10.5 percent YoY to 23.97 trillion yuan while imports climbed 4.3 percent YoY to 18.1 trillion yuan. China remained the largest trader in goods throughout the world for six successive years. China's trade in goods with the ASEAN, the EU and the US last year respectively surged 15 percent, 5.6 percent and 3.7 percent. China's trade with countries along the Belt and Road rose 19.4 percent YoY and accounted for 32.9 percent of nation's total foreign trade, up 3.2 percentage points. The country's trade with the other 14 members of the Regional Comprehensive Economic Partnership increased 7.5 percent.",
  'link': 'https://www.chinadaily.com.cn/a/202301/13/WS63c0bd6fa31057c47eba962e.html'},
 {'title': 'China Says It May Have Detected Signals From Alien Civilizations',
  'text': 'No summary available.',
  'link': 'https://www.bloomberg.com/news/articles/2022-06-15/china-says-it-may-have-detected-signals-from-alien-civilizations?leadSource=uverify%20wall'},
 {'title': "America dropped 26,171 bombs in 2016. What a bloody end to Obama's reign | Medea Benjamin",
  'text': 'President Obama did reduce the number of US soldiers fighting in Afghanistan and Iraq, but he dramatically expanded the air wars and the use of special operations forces around the globe. In 2016, the Obama administration dropped at least 26,171 bombs, which means that every day last year, the US military blasted combatants or civilians overseas with 72 bombs; that’s three bombs every hour, 24 hours a day. While most of these air attacks were in Syria and Iraq, US bombs also rained down on people in Afghanistan, Libya, Yemen, Somalia and Pakistan. That’s seven majority-Muslim countries. Obama authorized over 10 times more drone strikes than George W Bush, and automatically painted all males of military age in these regions as combatants, making them fair game for remote controlled killing.',
  'link': 'https://www.theguardian.com/commentisfree/2017/jan/09/america-dropped-26171-bombs-2016-obama-legacy'},
 {'title': 'China accuses US of ‘illegally’ flying balloons across its airspace',
  'text': "- China accuses US of 'illegally' flying balloons across its airspace, while the White House denies the claims. \n- Wang Wenbin, a Chinese foreign ministry spokesperson, also accused the US of frequently sending warships and planes to carry out close-range reconnaissance against China. \n- Maritime authorities in China’s Shandong province spotted an “unidentified flying object” above waters near the port city of Rizhao and were “preparing to shoot it down.”",
  'link': 'https://edition.cnn.com/2023/02/13/china/china-unidentified-flying-object-intl-hnk-mic/index.html'},
 {'title': 'Samsung could use ChatGPT in its phones to overtake iPhone’s Siri',
  'text': "- Samsung says it is open to working with ChatGPT to supercharge Bixby, its AI assistant, and make Samsung's phones and wearables much smarter. \n- With ChatGPT or Bard integration, Bixby could manage much more and have a much more conversational experience with users. \n- Samsung could possibly integrate ChatGPT-like tech into its Galaxy earbuds and perhaps its first mixed reality headset.",
  'link': 'https://www.tomsguide.com/news/samsung-could-use-chatgpt-in-its-phones-to-overtake-iphones-siri'},
 {'title': 'Is Apple prepping to launch a ChatGPT-esque search engine? I certainly think so',
  'text': '- Apple is planning to triple its self-build critical power capacity in 2023, potentially signaling it has compute-heavy new plans.\n- Apple may be looking to launch services that require more energy to run, like virtual/augmented reality or a bigger push in services.\n- Apple could terminate its lucrative search agreement with Google by launching its own ChatGPT-esque search engine with Siri at its core.',
  'link': 'https://www.techradar.com/news/could-apple-be-preparing-a-chatgpt-esque-search-engine-i-think-so'},
 {'title': 'Nu hoppar de kinesiska techjättarna på Chat GPT-tåget',
  'text': "- China's biggest tech companies, including Alibaba, Tencent, and Baidu, are all developing their own versions of ChatGPT-like bots.\n- Baidu is set to launch Ernie, a bot built on technology that has been under development since 2019.\n- Alibaba and Tencent are also working on their own versions.",
  'link': 'https://computersweden.idg.se/2.2683/1.776176/nu-hoppar-de-kinesiska-techjattarna-pa-chat-gpt-taget'},
 {'title': "Amazon CEO says ChatGPT is 'exciting,' but that Amazon has been working on similar tech for a long time",
  'text': "- Amazon's CEO Andy Jassy said generative AI like ChatGPT presents exciting possibilities.\n- Amazon has been working on generative AI for a long time, including Alexa and CodeWhisperer.\n- Amazon is also pursuing opportunities to partner with smaller firms to develop this area of the business.",
  'link': 'https://www.businessinsider.com/amazons-ceo-andy-jassy-on-chat-cpt-ai-2023-2?r=US&IR=T'},
 {'title': 'There’s now an open source alternative to ChatGPT, but good luck running it',
  'text': "PaLM + RLHF, an open-source text-generating model similar to ChatGPT, has been released, but it requires extensive resources and training to work. PaLM + RLHF uses Google's PaLM and a technique called Reinforcement Learning with Human Feedback to accomplish a variety of tasks. However, downloading the system does not provide a ChatGPT-like experience as the model is not pre-trained and requires compiling gigabytes of text from which the model can learn, and finding hardware capable of handling the training workload. The process of collecting and training the model data is also expensive.",
  'link': 'https://techcrunch.com/2022/12/30/theres-now-an-open-source-alternative-to-chatgpt-but-good-luck-running-it/'},
 {'title': "France to introduce 'porn passports' to verify age",
  'text': "France will introduce 'porn passports' in September 2023 to prevent minors from viewing explicit material. The 'porn passports' will be enforced through a government phone application that provides users with a digital certificate and code for age verification. Websites could face being banned if they fail to comply with age verification regulations. This follows the UK's debate over amendments to the Online Safety Bill to demand tougher age checks for pornography. A survey found that children as young as nine are exposed to graphic material online, with Twitter being the site where the highest proportion of young people access sexual content.",
  'link': 'https://www.dailymail.co.uk/news/article-11721729/France-introduce-porn-passports-verify-age.html'},
 {'title': 'Analfabetism – det osynliga funktionshindret: Ett globalt problem',
  'text': "Nearly 800,000 people in Sweden lack sufficient reading and writing skills to function in society, according to Gulistan Kavak, a school counselor and author who has written a children's book called My Mom Can't Read and Write to increase awareness about illiteracy. Illiteracy, known as analfabetism in Swedish, is more common than many people think in the country. Kavak says that it becomes more difficult to learn how to read and write as one gets older and it is especially difficult for those who come from another country to learn a new language.",
  'link': 'https://www.tv4.se/klipp/va/13810210/analfabetism-det-osynliga-funktionshindret-ett-globalt-problem'},
 {'title': 'RCEP contributes to global trade, investment growth in past year-China International Import Expo',
  'text': 'No text provided',
  'link': 'https://www.ciie.org/zbh/en/news/exhibition/news/20230209/36310.html'},
 {'title': 'Roald Dahls böcker skrivs om – stötande ord tas bort',
  'text': '- Flera beskrivande adverb har plockats bort.\n- Augustus Gloop beskrivs i nyutgåvorna som ”enorm”, men får inte kallas ”fet”.\n- Oompa-Loompas har blivit könsneutrala.\n- ”Pojkar och flickor” har bytts ut mot ”barn” och Matilda läser inte längre Djungelboken.\n- Ingen karaktär får längre vara ”galen” eller ”tokig” utav respekt för de som lider av psykisk ohälsa och ”svart” och ”vitt” är bortplockat.',
  'link': 'https://www.expressen.se/nyheter/roald-dahls-bocker-skrivs-om-stotande-ord-tas-bort/'},
 {'title': 'Canada Leads World in Organ Donations from Euthanasia',
  'text': "- Canada is leading the world in harvesting organs from those who received medical assistance in dying.\n- Patients who choose a medically assisted death due to suffering from cancer cannot be organ donors.\n- Usable donors were suffering from diseases such as amyotrophic lateral sclerosis, Parkinson's disease or multiple sclerosis.\n- Almost half of those donors, 136, came from Canada.\n- There are concerns about the lack of oversight or data collection with regards to euthanasia in Canada.",
  'link': 'https://www.voanews.com/a/canada-leads-world-in-organ-donations-from-euthanasia/6926402.html'},
 {'title': 'Philippine fertility rate drops to less than 2 kids per woman',
  'text': "The Philippines' fertility rate dropped to below two children per woman of reproductive age, highlighting a demographic transition that could boost efforts to bring down poverty. The total fertility rate fell to 1.9 offspring per woman aged between 15 and 49 in 2022, from 2.7 in 2017, according to a survey published this week on the Philippine Statistics Authority's (PSA) website. Economic gains from the demographic transition can be funnelled to reduce poverty and improve labour force participation.",
  'link': 'https://www.straitstimes.com/asia/se-asia/philippine-fertility-rate-drops-to-less-than-2-kids-per-woman'},
 {'title': 'Avidbots raises $24M for commercial floor cleaning robots',
  'text': "Avidbots, a Canadian company that makes commercial floor cleaning robots, raised $23.6 million in Series B funding led by returning investor True Ventures. The company's first product, Neo, is an autonomous floor scrubbing robot designed for airports, warehouses, manufacturing sites, malls, and universities. After an initial facility-mapping process, Neo can autonomously clean an environment thanks to proprietary software, 3D sensors and cameras. Avidbots said its customers include Paris Charles de Gaulle Airport, Toronto's Eaton Centre mall, and Rochester Institute of Technology.",
  'link': 'https://www.therobotreport.com/avidbots-commercial-floor-cleaning-robots/'},
 {'title': 'ChatGPT passes MBA exam given by a Wharton professor',
  'text': "A new research conducted by a professor at the University of Pennsylvania's Wharton School found that the artificial intelligence-driven chatbot GPT-3 was able to pass the final exam for the school's Master of Business Administration (MBA) program. The bot scored between a B- and B on the exam, showing its remarkable ability to automate some of the skills of highly compensated knowledge workers in general and specifically the knowledge workers in the jobs held by MBA graduates including analysts, managers, and consultants.",
  'link': 'https://www.nbcnews.com/tech/tech-news/chatgpt-passes-mba-exam-wharton-professor-rcna67036'},
 {'title': 'A Chinese artificial intelligence program just beat humans in an IQ test',
  'text': "A new artificial intelligence (AI) program designed by Chinese researchers has beat humans on a verbal IQ test. Scoring well on the verbal section of the intelligence test has traditionally been a tall order for computers, but in a new study, the program did better than its human counterparts who took the test. Although it scored better than the average person in the study, it didn't fare so well against some participants, such as people 30 and over and people with a master's or doctorate degree.",
  'link': 'https://www.businessinsider.com/chinese-ai-beat-humans-in-an-iq-test-2015-6?r=US&IR=T'},
 {'title': 'ChatGPT passes exams from law and business schools',
  'text': "ChatGPT passed law exams in four courses at the University of Minnesota and another exam at University of Pennsylvania’s Wharton School of Business. It performed on average at the level of a C+ student. ChatGPT also passed a business management course exam at Wharton with a B to B- grade. Christian Terwiesch, a Wharton business professor, said ChatGPT did 'an amazing job' at answering basic operations management and process-analysis questions but struggled with more advanced prompts and made 'surprising mistakes' with basic math.",
  'link': 'https://edition.cnn.com/2023/01/26/tech/chatgpt-passes-exams/index.html'},
 {'title': 'Is this the end of Made in Europe?',
  'text': "Europe's manufacturing industry is facing an existential crisis due to high energy prices and competition from China and the US. Many manufacturing firms are struggling to remain competitive in Europe due to the cost of energy, particularly those in energy-intensive sectors like glass, chemicals, metals, fertilizer, pulp and paper, ceramics, and cement. The long-cherished vision of Europe as the driving force of a green industrial revolution has been thrown into serious doubt by Joe Biden’s $369 billion Inflation Reduction Act. Losing manufacturing capacity means losing jobs and risking Europe’s security of supply, export ability, and job creation. European leaders are calling for coordinated, EU-level action to rescue Europe’s manufacturing base.",
  'link': 'https://www.politico.eu/article/end-made-in-europe-manufacturing-industry-struggle/'},
 {'title': 'VW exec says high energy prices will kill car battery production in Europe',
  'text': "German car giant Volkswagen may stop investing in battery factories across the bloc if the EU fails to tame energy prices and beef up its industrial policy, according to a senior executive at the company. The VW executive called Europe's standing industrial subsidy programs outdated and bureaucratic, and said tentative plans by France's Economy Minister Bruno Le Maire and Germany's Vice Chancellor Robert Habeck to bolster Europe's support for its major industrial players will fall short.",
  'link': 'https://www.politico.eu/article/volkswagen-cars-battery-production-energy-prices-european-union/'},
 {'title': 'How robots are helping address the fast-food labor shortage',
  'text': 'Fast-food restaurant chains are adding robots to their kitchens using artificial intelligence, computer vision technology, and a mechanical arm. Up to 82% of restaurant positions could, to some extent, be replaced by robots. Other companies in the space include Picnic, whose pizza station can make up to 130 oven-ready pizzas per hour, and Autec, with a line of sushi robots.',
  'link': 'https://www.cnbc.com/2023/01/20/how-fast-food-robots-are-helping-address-the-labor-shortage.html'},
 {'title': '80% of restaurant jobs could be taken over by robots',
  'text': 'Up to 80% of restaurant jobs could be taken over by robots. Working in the office helps overcome inequalities. The role of the office remains essential, and working (at least part of your time) in the office has its advantages.',
  'link': 'https://www.adeccogroup.com/future-of-work/latest-insights/80-of-restaurant-jobs-could-be-taken-over-by-robots/'},
 {'title': '300 Japanese stores will be reshelved by robot arms next month',
  'text': "Telexistence Inc. announced a new partnership with the Japanese convenience store chain, FamilyMart, to deploy robots to reshelving the minimarts' refrigerated products. The TX-SCARA (short for “Selective Compliance Assembly Robot Arm”) is an autonomous restock bot capable of moving items from storage to fridge shelves, and was reportedly designed to help address the country’s ongoing labor shortage issues. Should things go awry behind-the-scenes, the TX-SCARA will also be able to fallback on human employees who remotely control the arms until the issue is addressed.",
  'link': 'https://www.popsci.com/technology/japan-robot-arms-reshelve-store/'},
 {'title': 'Self-driving start-up Pony.ai plans to mass produce robotrucks in China',
  'text': ['Pony.ai announces plans for mass production of autonomous trucks in China with Sany Heavy Industry.',
   'Annual production expected to reach about 10,000 trucks within a few years.',
   'Small-scale deliveries to start this year and next, mass production in 2024.',
   'Trucks to feature Level 4 autonomous driving technology.',
   "Current regulations don't allow fully autonomous operation; Pony.ai has testing permits in Beijing and Guangzhou.",
   "Nvidia Drive Orin chip used in Pony.ai's autonomous driving system."],
  'link': 'https://www.cnbc.com/2022/07/28/self-driving-tech-company-ponyai-plans-to-deliver-robotrucks-in-china.html'},
 {'title': 'Snapchat launches an AI chatbot powered by OpenAI’s GPT technology',
  'text': ["Snapchat introduces 'My AI', a chatbot using OpenAI's GPT technology for its Snapchat+ subscription service.",
   'My AI can help with trivia, write haikus, and more, with a focus on friendship, learning, and fun.',
   "Adheres to app's trust and safety guidelines but acknowledges potential deficiencies.",
   'Conversations stored for product improvement; users advised not to share secrets or rely on advice.',
   'AI chatbot designed to foster deeper connections and possibly boost paid subscriber numbers.'],
  'link': 'https://techcrunch.com/2023/02/27/snapchat-launches-an-ai-chatbot-powered-by-openais-gpt-technology/'},
 {'title': 'TikTok owner is giving new app Lemon8 a shot despite',
  'text': ['ByteDance introduces Lemon8, a daily life guide photo-sharing app, in the US and UK.',
   "Pays influencers to post content; aims to emulate Xiaohongshu's success in China.",
   'Lemon8 focused on community-driven content and user-generated reviews, tips, and more.',
   'Top lifestyle app in Thailand and Indonesia, but faces competition from Instagram and Pinterest.',
   "Success in North America and Europe may be challenging due to varying user behavior and TikTok's data security concerns."],
  'link': 'https://en.pingwest.com/a/11434'},
 {'title': "PDD's online dollar store, Temu, to launch services in Australia and New Zealand soon",
  'text': ['Temu, owned by PDD Holdings, is set to launch in Australia and New Zealand on March 13',
   'Temu offers a variety of products at low prices, competing with Chinese fast fashion retailer Shein',
   'The company aims for $30 billion GMV in the next five years',
   "Temu is now focusing on increasing per-customer spending, currently at $25 compared to Shein's $75",
   'Credit Suisse estimates Temu could sell $3.6 billion worth of goods in 2023 but incur a $1.7 billion operating loss'],
  'link': 'https://en.pingwest.com/a/11455'},
 {'title': 'Opera browser to integrate ChatGPT via OpenAI · TechNode',
  'text': ['Opera browser is set to integrate ChatGPT via OpenAI',
   'Article does not provide additional details about the integration'],
  'link': 'https://technode.com/2023/03/01/opera-browser-to-integrate-chatgpt-via-openai/'},
 {'title': 'DuckDuckGo dabbles with AI search',
  'text': ['DuckDuckGo launches AI-powered summarization feature called DuckAssist in beta',
   'Utilizes natural language technology from ChatGPT-maker OpenAI and Anthropic',
   "Currently available via DuckDuckGo's apps and browser extensions, with plans for wider rollout",
   'Feature helps users find factual information more quickly, sourcing answers mainly from Wikipedia',
   'Privacy-focused with anonymous search and no data sharing with third parties'],
  'link': 'https://techcrunch.com/2023/03/08/duckassist/'},
 {'title': 'Brave Search launches an AI-powered summarization feature',
  'text': ["Brave Search introduces new 'Summarizer' feature, not powered by OpenAI's GPT tech.",
   'Feature provides synopsis of search queries using multiple sources.',
   'Available for desktop and mobile users, accessible through any browser.',
   'Improved Brave Search highlights relevant sentences in listed results.',
   "Brave Search's LLM trained to combat 'unsubstantiated assertions'.",
   'Currently applicable to 17% of search engine queries, expected to increase.'],
  'link': 'https://techcrunch.com/2023/03/02/brave-search-launches-an-ai-powered-summarization-feature/'},
 {'title': "India's Oil Deals With Russia Dent Decades-Old Dollar Dominance",
  'text': ["Sanctions on Russia erode dollar's dominance in international oil trade.",
   "India, world's third-largest oil importer, shifts to non-dollar currencies for Russian oil.",
   'Transactions in non-dollar currencies total several hundred million dollars in the past three months.',
   'Indian banks and Russian suppliers determined to continue oil trade despite sanctions.',
   'Dollar dominance faces potential erosion due to geopolitical tensions and formation of smaller trading blocs.'],
  'link': 'https://money.usnews.com/investing/news/articles/2023-03-08/indias-oil-deals-with-russia-dent-decades-old-dollar-dominance'},
 {'title': 'Will Russia sanctions dethrone ‘King Dollar’?',
  'text': ['US dollar has dominated global trade for nearly eight decades, but recent events have countries exploring alternatives.',
   "Russia's invasion of Ukraine and subsequent US-led sanctions have triggered efforts to reduce dependence on the dollar.",
   'Countries fear the US could use its currency power to target them as it has with Russia.',
   "Dollar's dominance is unlikely to change soon, but its grip could weaken as more countries trade in other currencies.",
   'De-dollarization initiatives have increased, with nations like India, Brazil, South Africa, and Argentina seeking alternatives.'],
  'link': 'https://www.aljazeera.com/features/2023/3/7/will-russia-sanctions-dethrone-king-dollar'},
 {'title': 'China’s first photonic chip production line to be ready in 2023: media report',
  'text': ["China's first production line for multi-material and cross-size photonic chips to be completed in 2023.",
   'Photonic chips offer higher speeds and lower power consumption compared to electronic chips.',
   "The facility, built by Sintone, aims to fill a gap in China's top-level manufacturing.",
   'Photonic chips are used in communications, data centers, medical testing, and other sectors.',
   "China's photonic chip market expanded from $800 million in 2015 to $2.08 billion in 2021."],
  'link': 'https://www.globaltimes.cn/page/202210/1277405.shtml'},
 {'title': 'Photonic System-on-Chip is the Future',
  'text': 'EFFECT Photonics is using a photonic System-on-Chip (SoC) approach to integrate all optical components on a single chip. This approach helps minimize losses, reduce assembly complexity, and lower costs. By testing the dies and wafers directly before packaging, manufacturers save time, cost, and energy. Photonic SoCs have limitless and priceless real-world applications and are particularly useful in data center interconnects.',
  'link': 'https://effectphotonics.com/insights/photonic-system-on-chip-is-the-future/'},
 {'title': 'Hello Dolly: Democratizing the magic of ChatGPT with open models',
  'text': 'Dolly is a cheap-to-build LLM that exhibits a surprising degree of the instruction following capabilities exhibited by ChatGPT. We believe models like Dolly will help democratize LLMs, transforming them from something very few companies can afford into a commodity every company can own and customize to improve their products. Dolly is a 6 billion parameter model trained on high-quality training data that can be fine-tuned to exhibit ChatGPT-like interactivity. The release of Dolly is the first in a series of announcements Databricks is making that focus on helping every organization harness the power of large language models.',
  'link': 'https://www.databricks.com/blog/2023/03/24/hello-dolly-democratizing-magic-chatgpt-open-models.html'},
 {'title': "China's U.S. Treasury holdings hit 12-year low on rate hikes, tensions",
  'text': "- China's holdings of Treasury securities fell for the fifth straight month in December to $867 billion, hitting the lowest level in over 12 years. \n- The decline in holdings is attributed to American interest rate hikes and bilateral tensions. \n- However, China's gold trove grew during this period. ",
  'link': 'https://asia.nikkei.com/Business/Markets/Bonds/China-s-U.S.-Treasury-holdings-hit-12-year-low-on-rate-hikes-tensions'},
 {'title': 'CATL secures deal for 450MWh storage project in Texas· TechNode',
  'text': "- CATL signed an agreement with HGP Storage to supply around 450 megawatt-hours of lithium-ion batteries for a Texan energy storage operation. \n- CATL's containerized liquid-cooling battery system will power the facility, which will store up to 450 MWh of electricity in a single cycle and will begin operation in 2024. \n- Energy storage is the second biggest revenue source for CATL, accounting for about 14% of its total revenue in 2022. ",
  'link': 'https://technode.com/2023/03/28/catl-secures-deal-for-450-mwh-storage-project-with-hgp-in-texas/'},
 {'title': 'TikTok ban backup plan? ByteDance-owned Instagram rival Lemon8 hits the US App Store’s Top 10',
  'text': '- ByteDance-owned app Lemon8, an Instagram rival, jumped into the U.S. App Store’s Top Charts, becoming the No. 10 Overall app, across both apps and games. \n- The move is likely due to a recent significant user acquisition push by the app publisher, though data on U.S. installs are not yet available. \n- The app has gained 16 million global downloads since its debut in March 2020, with Japan as its top market, accounting for 38% of its total installs. ',
  'link': 'https://techcrunch.com/2023/03/28/tiktok-ban-backup-plan-bytedance-owned-instagram-rival-lemon8-hits-the-u-s-app-stores-top-10/'},
 {'title': 'Why are AI models getting cheaper as they improve? · TechNode',
  'text': ['Large-scale AI models like GPT are seeing falling costs',
   'Decreasing cost of large AI models is mainly due to the continuous advancement of technology and intensification of competition',
   'Market competition has become intense, and price competition has also begun',
   'Algorithmic improvements, hardware improvements, dataset size, reusable pre-trained models, and distributed computing are driving cost reductions in large AI models',
   "AI's development is strongly positively correlated with Moore's law of chips"],
  'link': 'https://technode.com/2023/03/27/why-are-ai-models-getting-cheaper-as-they-improve/'},
 {'title': 'GitHub slashes engineering team in India',
  'text': ['GitHub has laid off virtually its entire engineering team in India',
   'The developer firm has eliminated over 100 jobs in the South Asian market',
   'The layoff is part of the streamlining effort the firm had disclosed in February',
   'GitHub had said that it would cut roughly 10% of its workforce by the quarter ending in March',
   "India is one of the world's largest developer markets and a key engineering hub for many large companies"],
  'link': 'https://techcrunch.com/2023/03/27/github-slashes-engineering-team-in-india/'},
 {'title': 'Twitter is dying',
  'text': "Since Elon Musk bought Twitter, he has set about dismantling everything that made Twitter valuable, making it his mission to drive out expertise, scare away celebrities, bully reporters and reward the bad actors, spammers and sycophants who thrive in the opposite environment. Twitter is no longer free. Musk has applied his vast wealth to destroying as much of the information network's value as possible in as short a time as possible. Musk rips away the last layer of legacy verification, turning up the volume on anyone who’s willing to pay him $7.99 per month to shout over everyone else. Genuine users are rightly outraged at the idea of being blackmailed into paying Musk to prove who they are.",
  'link': 'https://techcrunch.com/2023/03/28/twitter-is-dying/'},
 {'title': 'Nvidia Tech Uses AI to Optimize Chip Designs up to 30X Faster',
  'text': "Nvidia has developed AutoDMP, a system that can accelerate modern chip floor-planning using GPU-accelerated AI/ML optimization, resulting in a 30X speedup over previous methods. AutoDMP delivers a very similar placement plan to experts using the latest Electronic Design Automation (EDA) layout design tools. Macro placement has a significant impact on the landscape of the chip, 'directly affecting many design metrics, such as area and power consumption'. AutoDMP is open source, with the code published on GitHub.",
  'link': 'https://www.tomshardware.com/news/nvidia-tech-uses-ai-to-optimize-chip-designs-up-to-30x-faster'},
 {'title': 'Goda skäl för ”Ernie” att hålla tyst',
  'text': '- En kinesisk AI-bot som kallats Kinas svar på Chat GPT, Ernie, fungerar inte tillfredsställande och har fått negativ kritik på sociala medier. \n- Bildbehandling i kinesiska tecken ställer till det för Ernie att svara korrekt. \n- Techjätten Baidu som utvecklat Ernie har mer att jobba på.',
  'link': 'https://www.svd.se/a/JQLl8b/goda-skal-for-ernie-att-halla-tyst'},
 {'title': '”Vi tror inte på Gud – men han gav oss detta land”',
  'text': '- Konflikten mellan Netanyahu och demonstranterna i Israel pågår och splittrar befolkningen i landet. \n- Jerusalem är en stad med rik historia, kultur och religiösa motsättningar. \n- Frågan om hur staten Israel kan vara både judisk och demokratisk är en central del av kulturkriget som pågår.',
  'link': 'https://www.svd.se/a/mQVxX4/vi-tror-inte-pa-gud-men-han-gav-oss-detta-land'},
 {'title': 'UAE, KSA, India, South Korea secretly supplying missiles to Ukraine',
  'text': '- Flera länder skickar missiler i hemlighet till Ukraina för att upprätthålla sina ekonomiska intressen med Ryssland. \n- Officiellt neutrala regeringar har använt sina militära lager för att kompensera bristen på västerländska vapen under konflikten i Ukraina. \n- Länder som UAE, Saudiarabien, Qatar, Indien, Finland och Sydkorea har skickat vapen till Ukraina, även om vissa länder har valt att hålla detta hemligt.',
  'link': 'https://english.almayadeen.net/news/politics/uae-ksa-india-south-korea-secretly-supplying-missiles-to-ukr'},
 {'title': 'Biden: Israel ‘cannot continue down this road’; no Netanyahu invite in ‘near term’',
  'text': ['US President Joe Biden urged PM Benjamin Netanyahu to walk away from his judicial overhaul legislation, saying he was “very concerned” about the health of Israeli democracy and warning that Israel “cannot continue down this road.”',
   "Biden emphasized the word “genuine” and said he wouldn't be inviting Netanyahu to the White House in the near term.",
   'Netanyahu responded by insisting that he was seeking to restore the “proper balance between the three branches of government” via consensus and declared that Israel would not make decisions based on overseas pressure, even from “the best of friends.”',
   "Biden's critical public comments seemed to go against his administration’s messaging over the past 24 hours, which had seen US officials repeatedly hail Netanyahu’s decision on Monday to suspend his coalition’s legislative effort to radically curb the High Court of Justice’s power and enter negotiations with the opposition to strike a compromise on judicial reform.",
   'The issue has played a role in the ongoing deterioration of ties between Israel and the US.'],
  'link': 'https://www.timesofisrael.com/biden-israel-cannot-continue-down-this-road-no-netanyahu-invite-in-near-term/'},
 {'title': 'That was fast! Microsoft slips ads into AI-powered Bing Chat',
  'text': "Microsoft is experimenting with sponsored responses in Bing Chat powered by OpenAI's GPT-4. The company is exploring additional capabilities, including expanded hover experience and placing ads in the chat experience to share the ad revenue with partners. The ads have been reported anecdotally for a couple of weeks but are not enabled for all users. Ads like these cannot be blocked with current tools and may erode trust, even with ad labels. The chat answer should not be tampered with, but there should be a better “meta-conversation” to the side of the chat that has its citations and, if they exist, its ads.",
  'link': 'https://techcrunch.com/2023/03/29/that-was-fast-microsoft-slips-ads-into-ai-powered-bing-chat/'},
 {'title': '',
  'text': 'Unable to load content due to disabled JavaScript in the browser.',
  'link': 'https://twitter.com/WatcherGuru/status/1642206765675687937'},
 {'title': 'New BRICS currency underway: State Duma Deputy Chairman',
  'text': "The BRICS alliance is working on creating its currency, and the readiness to realize this project will be announced at the leaders' summit. The currency would be secured not just by gold, but also by other groups of products, including rare-earth elements of the soil. Earlier today, China and Brazil struck a deal to ditch the US dollar in their bilateral transactions, which is expected to reduce investment costs and develop economic ties between the two countries. South Africa's international relations minister Naledi Pandor said today that her country will not cut ties with Russia as per the wishes of third parties or countries.",
  'link': 'https://english.almayadeen.net/news/politics/new-brics-currency-underway:-state-duma-deputy-chairman'},
 {'title': '',
  'text': 'Unable to load content due to disabled JavaScript in the browser.',
  'link': 'https://twitter.com/ItsShubhangi/status/1642349530887905280'},
 {'title': 'Malaysia, China to Discuss ‘Asian Fund’ to Cut US Dollar Dependency',
  'text': ['New era of business of sports underway, involving media, technology, finance, and real estate.',
   'Leagues and teams mature into more than just entertainment, impacting communities, cities, and countries.'],
  'link': 'https://www.bloomberg.com/news/articles/2023-04-04/malaysia-china-to-discuss-asian-fund-to-cut-dollar-dependency?utm_content=business&utm_medium=social&cmpid=socialflow-twitter-business&utm_source=twitter&utm_campaign=socialflow-organic'},
 {'title': 'Philippines’ approval of RCEP paves way for world’s largest trade deal, set to drive Asia-Pacific economic cooperation',
  'text': ["Philippines approves RCEP trade agreement, paving way for world's largest free trade area.",
   'RCEP will enhance market access and put the Philippines on par with other major economies.',
   'Trade between China and other RCEP members reached $1.88 trillion in 2022.',
   'RCEP members should strengthen cooperation in politics, economy, and cultural exchanges.'],
  'link': 'https://www.globaltimes.cn/page/202302/1286027.shtml'},
 {'title': 'Russia transferred nuclear-capable Iskander system to Belarus: MoD',
  'text': ['Russia supplies Belarus with Iskander missile system capable of using nuclear missiles.',
   'Belarusian units begin training on missile system to protect the Union State.',
   'Russian President Putin announced the placement of tactical nuclear weapons in Belarus.',
   'US considers providing Ukraine with ATACMS missiles and F-16 fighter jets.'],
  'link': 'https://english.almayadeen.net/news/politics/russia-transferred-nuclear-capable-iskander-system-to-belaru'},
 {'title': 'Cocos raises $50M to fuel open source game engine growth',
  'text': 'Cocos Technology has raised $50 million in funding to improve the core technology of its open source Cocos Creator game engine and promote its integration within various industries such as games, automobiles, education, XR, home design, architectural engineering design, and other future endeavors. The Cocos engine is a popular open-source engine used by over 1.4 million developers to date, with over 100,000 games in the app stores using it, and more than 1.6 billion people play games that use the engine.',
  'link': 'https://venturebeat.com/games/cocos-raises-50m-to-fuel-open-source-game-engine-growth/'},
 {'title': 'Chinese anime and game artists lose jobs because of the rise of AI-generated art',
  'text': "AI-generated art is causing negative impacts on China's gaming and animation industries, with many animators and game artists losing their jobs recently. The backlash from anime fans and communities has been swift, reflecting real fears about being copied or automated out of a job. Almost 30% of workers have been let go as a result of ongoing layoffs that occurred in the first three months of this year.",
  'link': 'https://en.pingwest.com/a/11577'},
 {'title': 'Chinese appliance giant Midea breaks ground on its third factory in Brazil',
  'text': "Midea Group has broken ground on a new facility in Brazil that covers an area of over 70,000 square meters and has an annual production capacity of 1.3 million units. With a total investment of more than 700 million yuan ($101.8 million), this is Midea's third plant in Brazil and will feature advanced digital and innovative production technologies. The first smart refrigerators are scheduled to go into production in July 2024 and will be sold to Brazil and other South American markets.",
  'link': 'https://en.pingwest.com/w/11597'},
 {'title': 'JD reorganizes retail team in low price strategy push · TechNode',
  'text': ['- JD reorganizes its retail team.',
   '- The move aims to push low price strategy.'],
  'link': 'https://technode.com/2023/04/12/jd-shuffles-retail-team-in-low-price-strategy-push/'},
 {'title': 'The Digital Currency Monetary Authority (DCMA) Launches an International Central Bank Digital Currency (CBDC)',
  'text': ['- DCMA announces the launch of an international CBDC at IMF Spring Meetings 2023.',
   '- Universal Monetary Unit (UMU) aims to strengthen monetary sovereignty of participating central banks.',
   '- UMU can transact in any legal tender and enforce banking regulations.',
   '- Aims to improve cross-border payments and transform foreign exchange transactions.'],
  'link': 'https://www.prnewswire.com/news-releases/the-digital-currency-monetary-authority-dcma-launches-an-international-central-bank-digital-currency-cbdc-301793163.html'},
 {'title': 'Ukrainian diplomat on why Russia is interested in a coup in Sudan',
  'text': ["- Skirmishes between Sudan's regular army and Rapid Reaction Force (RSF) began on April 15.",
   '- RSF leader Dagalo had an agreement with Russia for a naval base in Sudan.',
   '- Russia may support General Dagalo to implement their plans in Sudan.',
   "- Naval base would provide access to the Red Sea and control over South Sudan's oil exports.",
   "- Russia's Wagner Group mercenaries present in Sudan to extract natural resources."],
  'link': 'https://news.yahoo.com/ukrainian-diplomat-why-russia-interested-142800860.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAK8sYjUz5ZZZxK7Z_cmyRFPVT4ieemIDeJQ1PFfl9VmA_kkcNYblMoBo4doYrObmZGOVUy0Pp0XpE5atHCLuFkLXZI8HwHP0NXx5alXUtw8k6m-BIiQZxqKKXMDk_Gp8X1MjokbHDmgmK4ZRa1Rzm9Yxeww6rlOX76NDU4v59JkQ'},
 {'title': 'Grimes Offers 50% Royalties on AI-Generated Music Using Her Voice',
  'text': 'Grimes is offering a 50% royalty split to anyone who uses her voice on a successful AI-generated song. She has no label or legal bindings and is creating a program to simulate her voice. Grimes believes in open sourcing all art and killing copyright.',
  'link': 'https://decrypt.co/137649/grimes-offers-50-royalties-on-ai-generated-music-using-her-voice'},
 {'title': "'It's going to hit the consumer hard': Those with higher credit scores may pay higher mortgage fees",
  'text': "Changes in the mortgage industry may result in some people with higher credit scores paying a higher fee, while those with lower scores pay less. The Federal Housing Finance Agency is recalibrating the fee structure for loan-level price adjustment. This is part of the federal government's effort to provide equitable access to homeownership. The changes will also make it more expensive for borrowers to refinance and to pull equity out of their homes to pay off consumer debt.",
  'link': 'https://www.cbsnews.com/boston/news/mortgage-fee-changes-good-high-credit-scores/'},
 {'title': 'Savr tar in 162 miljoner – siktar på aktiehandel',
  'text': 'Swedish fintech company Savr has raised SEK 162m ($19m) in funding to develop an investment platform, including stock trading, in addition to its fund platform. Savr offers funds at lower fees by paying back fund commissions to savers. Savr has attracted over 90,000 customers in just over two years, and has repaid over SEK 17.5m ($2m) to its customers. The funding round was led by Schibsted and included Nordic Angels. SEB Corporate Finance Growth advised Savr on the fundraising.',
  'link': 'https://www.realtid.se/savr-tar-in-162-miljoner-siktar-pa-aktiehandel/'},
 {'title': 'Freetrade lanserar courtagefri handel av svenska aktier',
  'text': 'Freetrade has launched in Sweden, offering over 200 of the most popular Swedish stocks for fee-free trading on an ISA. Freetrade originally launched in the UK in 2018 and has over 1.4 million customers with £1.4bn ($1.9bn) in assets under administration.',
  'link': 'https://www.realtid.se/freetrade-lanserar-courtagefri-handel-av-svenska-aktier/'},
 {'title': 'Gen Z Ranks Watching TV, Movies as Fifth Among Top 5 Entertainment Activities',
  'text': '- Among Gen Z consumers in the U.S. (those currently aged 14-24), video games are their No. 1 entertainment activity — and watching TV or movies at home comes in fifth.\n- Only 10% of Gen Z respondents said watching TV or movies was their favorite entertainment pastime, the Deloitte study found.\n- Top 5 Entertainment Activities of U.S. Consumers by Age Group Source: Deloitte Media Trends survey, 15th Edition\n- U.S. consumers on average have access to four paid video streaming services; 82% subscribe to at least one paid streaming video service.\n- Content (35%) and cost (46%) are the most important factors in deciding to subscribe to a new paid streaming video service.',
  'link': 'https://variety.com/2021/digital/news/gen-z-survey-deloitte-tv-movies-ranking-1234954207/'},
 {'title': 'YouTube Will Now Enable Users to Watch Thousands of TV Shows, for Free, in the App',
  'text': '- YouTube has launched a new slate of TV shows in the app that users will be able to watch for free, with ads.\n- US viewers for the first time will be able to watch full seasons of TV shows on YouTube for free with ads.\n- Viewers will be able to tune in to a huge range of content, at any time, for free, so long as they can put up with a few ads in relevant gaps.\n- Connected TV viewing is now YouTube’s fastest growing usage category, and millions of users are now watching YouTube content on their home TV sets.\n- It’ll also significantly add to YouTube’s ad inventory, providing new opportunities for brands to reach viewers in the app with TV-like campaigns, at a much more affordable price, and with a lot more targeting options.\n- This is an important, and significant development, which is worth noting within the broader digital shift.',
  'link': 'https://www.socialmediatoday.com/news/youtube-will-now-enable-users-to-watch-thousands-of-tv-shows-for-free-in/620921/'},
 {'title': 'The future of streaming is ads',
  'text': ['Streaming services growth has slowed, and investors are uncertain about its profitability.',
   'Free ad-supported platforms like Tubi, Pluto, and The Roku Channel are now gaining traction.',
   'Two types of free streaming services: FAST (Free Ad-Supported Streaming Television) and AVOD (Advertising-Based Video On Demand).',
   '44% of people canceled at least one paid service in the last six months, and 59% of users are willing to watch ads for a cheaper or free subscription.',
   'Netflix and other platforms are introducing ad-supported plans.',
   'Free streaming services focus on user engagement and personalization.',
   "Though free streaming services may lack brand loyalty and big hits, Tubi and Amazon's Freevee are starting to produce more ambitious content."],
  'link': 'https://www.theverge.com/2023/4/29/23702827/free-streaming-services-tubi-pluto-roku'}

    ]

    # Insert the articles
    insert_articles(es, index_name, articles_to_insert)